### ISSUE TITLE
Fields within cards get column property (width) overriden

### ISSUE THREAD

**Issue by KuRen** [AntonioLoureiro/VueJS.jl#59]
**Example**: 2 fields, field1 and field2, on the same row of a card, with cols = 3 and cols = 9, respectively, get displayed with classes col-md-6 and col-md-18, also respectively.

```julia
function test(req)
    @el(field1, "v-text-field", label = "Field 1", value = "Value 1", cols = 3)
    @el(field2, "v-text-field", label = "Field 2", value = "Value 2", cols = 9)
    
    return response(page(card([[field1, field2]], cols = 6)))
end
```

![image](https://user-images.githubusercontent.com/6925634/102626472-bd9ea280-413e-11eb-9b31-d2028c5d3157.png)

Class values differ for cards of different widths. For instance, a card with cols = 7 generates fields with classes col-md-5 and col-md-15.

**Comment by KuRen** [comment]
This issue remains unsolved when a card element is contained in an array. 

**Example**:
```julia
function test(req)
    @el(field1, "v-text-field", label = "Field 1", value = "Value 1", cols = 3)
    @el(field2, "v-text-field", label = "Field 2", value = "Value 2", cols = 9)
    
    return response(page([card([[field1, field2]], cols = 6)]))
end
```
![image](https://user-images.githubusercontent.com/6925634/109832791-9b45fc80-7c38-11eb-9bd2-94938b392a15.png)

**Comment by AntonioLoureiro** [comment]
When you have a fixed cols for a holder, in the example cols=6 for card, the elements are correctly trying to be it's original width, you cannot put a 12 width elements (3+9) in a card with cols=6. The elements always try to maintain it's original size.
3/(6/12)=6 ; 9/(6/12)=18

But there was a bug in the resize, now fixed with:
https://github.com/AntonioLoureiro/VueJS.jl/commit/90a792a5270c14458bbe8f6c63951e0311433e95

This will allow in the near future Float cols

**Comment by charlieIT** [comment]
> When you have a fixed cols for a holder, in the example cols=6 for card, the elements are correctly trying to be it's original width, you cannot put a 12 width elements (3+9) in a card with cols=6. The elements always try to maintain it's original size.
> 3/(6/12)=6 ; 9/(6/12)=18
> 
> But there was a bug in the resize, now fixed with:
> [90a792a](https://github.com/AntonioLoureiro/VueJS.jl/commit/90a792a5270c14458bbe8f6c63951e0311433e95)
> 
> This will allow in the near future Float cols

Well, actually, wouldn't it be easier to just work with native definitions of css columns instead of applying these kind of factors and recalculations?

When we define a generic @el of 3 columns, we aren't actually saying the element will always occupy 3 columns inside any parent, we are saying it should occupy 3 columns in relation to a grid of 12 in any parent. 

If a parent is cols=6, it just means that it should occupy 50% of the available space, for instance half of a page, but the elements inside it are still sized in relation to 12. So, 9cols + 3 cols inside a 6 cols parent should mean that the elements keep their original columns, but will occupy 100% percent of the available visual space. 
It should not mean that the overall sum of child's columns for that card is 6.

For cases where the child's sum of columns is < 12, let's say cols = 7 and cols = 2 (which do not entirely fill the parent as 7 + 2 < 12), for a parent where cols = 4, then the 7 col element should fill 58% of the parent and the 2 cols element should fill 16%. This means that the parent card, of cols = 4, would have 25% of free space, but still visually occupy 4 columns. 

Another case, for 3 elements with cols = 4, inside a parent of cols = 11.
The parent should occupy 91% of available space in a row but it's children, which occupy 4 columns each, will completely fill the parent.

**Comment by AntonioLoureiro** [comment]
Short answer no, vuestructs and vuelements are reusable.
Long answer call me.

**Comment by charlieIT** [comment]
> > When you have a fixed cols for a holder, in the example cols=6 for card, the elements are correctly trying to be it's original width, you cannot put a 12 width elements (3+9) in a card with cols=6. The elements always try to maintain it's original size.
> > 3/(6/12)=6 ; 9/(6/12)=18
> > But there was a bug in the resize, now fixed with:
> > [90a792a](https://github.com/AntonioLoureiro/VueJS.jl/commit/90a792a5270c14458bbe8f6c63951e0311433e95)
> > This will allow in the near future Float cols
> 
> Well, actually, wouldn't it be easier to just work with native definitions of css columns instead of applying these kind of factors and recalculations?
> 
> When we define a generic @el of 3 columns, we aren't actually saying the element will always occupy a fixed size on any parent, we are saying it should occupy 3 columns in relation to a grid of 12 in any parent.
> 
> If a parent is cols=6, it just means that it should occupy 50% of the available space, for instance half of a page, but the elements inside it are still sized in relation to 12. So, 9cols + 3 cols inside a 6 cols parent should mean that the elements keep their original columns, and will correctly occupy 100% percent of the available visual space.
> It should not mean that the overall sum of child's columns for that card is 6, i.e, that cols > 6 is not possible inside a parent of 6.
> 
> For cases where the child's sum of columns is < 12, let's say cols = 7 and cols = 2 (which do not entirely fill the parent as 7 + 2 < 12), for a parent where cols = 4, then the 7 col element should fill 58% of the parent and the 2 cols element should fill 16%. This means that the parent card, of cols = 4, would have 25% of free space inside it, but still visually occupy 4 columns of the page.
> 
> Another case, for 3 elements with cols = 4, inside a parent of cols = 11.
> The parent should occupy 91% of available space in a row but it's children, which occupy 4 columns each, will completely fill the parent.

Closed as fictional and derivative

**Comment by charlieIT** [comment]
updated column logic to allow float values and greater control of element sizing
5c3f682938f5d38ae02b80c2839e314f739b381e
